#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -o Glycine_max.vs.TARGET_output
#PBS -e Glycine_max.vs.TARGET_error

set -u

# import BLAST module
module load LAS/ncbi-blast/2.4.0+

cd $PBS_O_WORKDIR

database_dir=protein_database/TARGET.faa.db

outfile=GM_TARGET.txt
echo -e "qseqid\tsseqid\tevalue\tbitscore\tqstart\tqend\tsstart\tsend" > $outfile
blastp \
   -query protein_sequences/Glycine_max.faa \
   -db $database_dir/TARGET.faa.db \
   -num_threads 16 \
   -outfmt '6 qseqid sseqid evalue bitscore qstart qend sstart send' >> $outfile
