#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=48:00:00
#PBS -o Glycine_max.vs.DATABASE_output
#PBS -e Glycine_max.vs.DATABASE_error

set -u

# import BLAST module
module load LAS/ncbi-blast/2.4.0+

cd $PBS_O_WORKDIR

outfile=GM_DATABASE.txt
echo -e "qseqid\tsseqid\tevalue\tbitscore\tqstart\tqend\tsstart\tsend" > $outfile
blastp \
   -query Glycine_max.faa \
   -db DATABASE/DATABASE \
   -num_threads 16 \
   -outfmt '6 qseqid sseqid evalue bitscore qstart qend sstart send' >> $outfile
