#!/bin/bash
#PBS -l nodes=1:ppn=16
#PBS -l walltime=00:05:00
#PBS -o Glycine_max.vs.TARGET_output
#PBS -e Glycine_max.vs.TARGET_error

set -u

# TODO import BLAST module

cd $PBS_O_WORKDIR

for database in *.db
do                                                                             
    outfile=GM_$database.txt
    echo 'qseqid sseqid evalue bitscore qstart qend sstart send' > $outfile
     blastp \
        -query Glycine_max.faa \
        -db $database/$database \
        -num_threads 2 \
        -outfmt '6 qseqid sseqid evalue bitscore qstart qend sstart send' >> $outfile &
done

wait
